ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:main:Exception on / [GET]
Traceback (most recent call last):
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\cenvs\sounds\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "..\main.py", line 21, in index
    readme_file = open("README.md", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
ERROR:main:Exception on / [GET]
Traceback (most recent call last):
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\cenvs\sounds\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "..\main.py", line 21, in index
    readme_file = open("README.md", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:main:Exception on / [GET]
Traceback (most recent call last):
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\cenvs\sounds\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "..\main.py", line 21, in index
    readme_file = open("README.md", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
ERROR:main:Exception on / [GET]
Traceback (most recent call last):
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\cenvs\sounds\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\cenvs\sounds\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "..\main.py", line 21, in index
    readme_file = open("README.md", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
ERROR:root:DB connection failed, check DB creadentials in config.json
